# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

orbs:
  typetalk: nulab/typetalk@1.1.0

jobs:
  build:
    docker:
      - image: circleci/node:10

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run build:ci

      - store_artifacts:
          path: dist

      - store_artifacts:
          path: reports

      - store_test_results:
          path: reports

      - typetalk/status:
          topic-id: "54145"
